---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "{{PETSITE_SA_ROLE}}"
  name: petsite-sa
  namespace: petadoptions
---
apiVersion: v1
kind: Service
metadata:
  name: service-petsite
  namespace: petadoptions
  annotations:
    scrape: "true"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  selector:
    app: petsite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petsite-deployment
  namespace: petadoptions
spec:
  selector:
    matchLabels:
      app: petsite
  replicas: 2
  template:
    metadata:
      labels:
        app: petsite
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: petsite
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: petsite
      serviceAccountName: petsite-sa
      containers:
      - image: "{{ECR_IMAGE_URL}}"
        imagePullPolicy: Always
        name: petsite
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: xray-service.petadoptions:2000
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: petsite-tgb
  namespace: petadoptions
spec:
  serviceRef:
    name: service-petsite
    port: 80
  targetGroupARN: "<arn-to-targetGroup>"
  targetType: ip
